### ISSUE TITLE
Changelog (upgrading React)

### ISSUE THREAD

**Issue by fcano-ut** [sealninja/react-i18nify#297]
Hello. In our project we're using version 1.11.18 of this library, but lists react 16 as a peerDependency. In order to update to React 17, we'd like to update the library and make any necessary change.

I found there's no changelog to know what are the differences between versions 1 to 2, 2 to 3, etc.. until current version. I saw a similar issue https://github.com/sealninja/react-i18nify/issues/56, but seems to have been resolved by the dev printing a list of the changes in a comment. That issue was from when the latest version was version 2, so its outdated.

Is there a way to know all breaking changes between all this releases? And I'm specially interested in arriving at the latest release with support for React 17

Thanks!

**Comment by mastacheata** [comment]
In v2 the library changed it's syntax, it no longer exports an I18n object but instead the translate and localize (with single letter alias t/t) directly.
Also the Translate compnent has lost the ability to render HTML/React Components. If you want that, you need to do it yourself with a span element the dangerouslySetInnerHtml attribute and the translate function.

Somewhere along the line they switched the date library for localization from monentJS to date-fns and in v7 to day.js.
You might want to replace moment.js anyway if you're upgrading from React 16.

**Comment by fcano-ut** [comment]
Thanks for the reply @mastacheata , I appreciate you taking the time to write this. I'll close this issue now.
