### ISSUE TITLE
I18n.js requires`moment` which is a devDependency

### ISSUE THREAD

**Issue by flo-sch** [sealninja/react-i18nify#42]
https://github.com/JSxMachina/react-i18nify/blob/master/src/lib/I18n.js#L118

`moment` is required but defined as a devDependency in package.json.

This method is internally used within `<Localize />` component.

In a project where `moment` itself is not included, it cause compilation warnings.

> WARNING in ./node_modules/react-i18nify/build/lib/I18n.js
> Module not found: Error: Can't resolve 'moment' in '/[...]/node_modules/react-i18nify/build/lib'
>  @ ./node_modules/react-i18nify/build/lib/I18n.js 131:21-38
>  @ ./node_modules/react-i18nify/build/index.js
>  @ ./node_modules/react-redux-i18n/build/index.js
>  @ ./src/app.js

**Quickfix** : set `moment` as a `dependency` instead of a `devDependency` in package.json.

I can propose a PR for that, but I wanted to discuss about it first.

`moment.js` (+ locales, + timezone) is quite a huge library, consuming {most of the time} un-necessary bandwidth.

The point of including it is to use its `format()` method, which is IMO quite an overkill here.

An alternative would be to use the lighter `date-fns` library : https://date-fns.org/, from which we can easily import the `format()` method only. I am pretty sure it would massively reduce the compiled width of every project using `react-i18nify` :)
Think about it as `lodash` for dates.

Source code would obviously need a few adjustments :

```
// Using moment.js
const moment = require('moment');
require('moment/min/locales'); // Should it actually be imported by react-i18nify itself or should it be the responsibility of the project ?!

// _localize()
try {
  return moment(
    value,
    options.parseFormat,
    this._locale,
    Boolean(options.strictParse),
  ).format(this.t(options.dateFormat));
} catch (e) {
  console.error('moment.js error', e);
  return '';
}
```

--->

```
// Using date-fns
import format from 'date-fns/format'
import parse from 'date-fns/parse'
import 'date-fns/esm/locale' // Should it actually be imported by react-i18nify itself or should it be the responsibility of the project ?!

// _localize()
try {
  return format(
    parse(value),
    this.t(options.dateFormat),
    {
      locale: this._locale
    }
  );
} catch (e) {
  console.error('date-fns error', e);
  return '';
}
```

Pros  (of using `date-fns` instead of `momentjs`)

- Modular library and selected imports (es6-ready) : massive reduction of bundle size
- Manipulate native Date objects

Cons

- No "parseFormat" option (`date-fns/parse` accepts complete ISO 8601 formats as well as partial implementations)

(But I can't really see in which case a non-standard "parseFormat" has an interest here?)

What do you think about that?

**Comment by gerbenmeyer** [comment]
No need for a quick-fix, `moment` is currently a peer-dependency, meaning you have to install it yourself.

Using `date-fns` instead of `moment` would be awesome though, would be happy to see a PR for that!

**Comment by flo-sch** [comment]
Really sorry about that, completely missed the peerDependency here...

About `date-fns`, one other con is that it does not seem to know specific localized formats.
For instance `format(new Date(), 'LTS')` will not work.

In the meantime, I was thinking, maybe the best way would be to write some kind of generic interface allowing people to choose if they prefer `moment.js` or `date-fns` themselves (defaulting to `moment.js` to preserve BC).

However I am not sure how to do that in JavaScript ; I'll dig into it!

**Comment by gerbenmeyer** [comment]
Please have a look at how I check for `moment.js` in the last version (1.11.10). Maybe we can extend this and also check for `date-fns`? In this way, they hopefully also don't have to be peer dependencies.

**Comment by flo-sch** [comment]
Thanks for the tip, it this seems brillant (even though I didn't test it yet) :)

I'll try to submit the PR later in the afternoon

**Comment by gerbenmeyer** [comment]
Actually it seems that multiple people have issues with compilers and `moment.js` being conditional or missing. So I'm thinking that probably it's the best to only support `date-fns`, but then as a non-optional normal dependency. What do you think?

**Comment by flo-sch** [comment]
Performance wise, it seems the best option we have...

However, thinking about it, I am not sure about :
- display formats
- supported languages

At this point, if we make such a change, it could be for a new major version, because it might cause small BC problems because of the points listed above...

Didn't had time to dig into a conditional dependency at the moment but I will take it tomorrow. Maybe I'll found something interesting?!

**Comment by flo-sch** [comment]
What about :

https://stackoverflow.com/a/46543835

But maybe you already got that one?

**Comment by rkrv** [comment]
Coming here from #28.

I agree that that switching to date-fns would most likely cause a lot of bc issues. It might be a good idea to think about it in the future. Otherwise, perhaps including a time library of your choice via a plugin for <Localize /> component could work, too.

The try/catch and conditional loading solution is good, problem is that it results in warnings. I think what we should do is find a way to suppress those warnings.

**Comment by flo-sch** [comment]
Hey @rkrv, thanks for your input ;

> perhaps including a time library of your choice via a plugin for component could work, too

Do you have an idea how to build this in practice?

I just came up with a theory at the moment.

**Comment by rkrv** [comment]
```js
// Localize.js
export default class Localize extends Component {}
```

```js
// LocalizeDateFns.js
export default class LocalizeDateFns extends Localize {
  // Conditional import date-fns
}
```

```js
// LocalizeMomentJs
export default class LocalizeMomentJs extends Localize {
  // Conditional import moment.js
}
```

```js
// Somewhere in your code...
import Localize from './LocalizeMomentJs';
```

However, now that I think about it...

moment.js is imported in I18n.js in the `_localize` method. `<Translate />` component does not use this method.

It would make sense to split the functionality in I18n.js so that `<Translate />` does not know about this dependency.

I am guilty myself, though, since I use `I18n.t()` directly somewhere else in the project. I recognize that there are people using `I18n.l()`, so splitting it up would be a hassle.

What if perhaps you were able to import only the locales you need? Right now all of them are imported, which is too much.

**Comment by flo-sch** [comment]
Well, as far as I am concerned, I would actually vote to remove the locales import from this project and let users import it themselves... But this would be definitely highly BC breaking!

Interesting thought to build 2 different components, didn't think about that actually...

But then we would have to split I18n.js

@gerbenmeyer what do you think?

**Comment by rkrv** [comment]
Problem is that if you use `I18n.t()`, then you inherit the `moment.js` import with it, too. I think the solution @gerbenmeyer went with is good, we just need to improve it so that it doesn't throw warnings.

**Comment by gerbenmeyer** [comment]
As conditional imports give warnings, we basically have two options: 1) revert back to always importing moment + locales, or 2) do something breaking.

I would prefer to do something breaking then. The best option in my opinion in that case is to switch to `date-fns`. This doesn't break that much (only things like 'LTS' won't work anymore), but would cause the bundle to be a lot smaller, which is valuable for many people.

And in this way we also create the option to have a LocalizeMoment component later on. This could even be a separate package.

**Comment by flo-sch** [comment]
Another thing to keep in mind are supported locales :

- `date-fns` : 32 main locales
- `moment.js` : 120 locales (if we count all variations of "en-GB", "en-US", "fr-FR", "fr-CA" etc.)

Actually @gerbenmeyer I think it would be better that 1.X.X versions of `react-i18nify` does not include BC breaks or compilation warnings.

If we wish to evolve in another direction, wether it is to switch to `date-fns` or to support multiple libraries, I think we should start working on another main version.

`react-i18nify` has been downloaded > 151k times in 2017 (according to NPM), BC changes should be not taken too easily ;)

https://npm-stat.com/charts.html?package=react-i18nify&from=2016-01-01&to=2018-02-06

That being said, I'm ready to commit myself into working on another major version (even though I cannot support that charge all by myself, especially maintenance).

It would obviously require some documentation as well if that's the decision we make.

Despite `react-redux-i18n`, do you know which other packages are already distributing `react-i18nify`?
It might be interesting to get some insights from the eco-system, what do you think?

**Comment by gerbenmeyer** [comment]
My idea would be to revert back to always importing moment + locales in 1.X.X (so to be not breaking, and fix all warnings), and switch to date-fns in version 2.X.X.

**Comment by flo-sch** [comment]
Agreed! :)

I this case, I think we can close this issue for now, I open a PR for a 2.X.X version on which we can continue to discuss this furthermore.

**Comment by flo-sch** [comment]
Actually I can't open a PR without commits. Is it something you can do @gerbenmeyer?

Otherwise I will open one as soon as I can come with something interesting :)

**Comment by gerbenmeyer** [comment]
Cool, I'll revert the optional moment in 1.X.X

**Comment by gerbenmeyer** [comment]
Isn't the normal flow to fork, commit, and then PR?

**Comment by flo-sch** [comment]
Probably, opening a PR without commit was just in order to continue the discussion, but as you prefer. We can discuss after commits as well :)

**Comment by gerbenmeyer** [comment]
I didn't even know that was an option :stuck_out_tongue:

**Comment by flo-sch** [comment]
Just to note it somewhere, `date-fns` is currently working on a 2.0.0 (currently alpha-7) version which includes localized formats aswell.

I'll follow that :)

https://date-fns.org/v2.0.0-alpha.7/docs/format

**Comment by lyleunderwood** [comment]
Just want to add a data point to this discussion. I wanted to remove unnecessary moment locales from my webpack bundle, and in order to confirm the result I ran an analysis on that bundle:

![image](https://user-images.githubusercontent.com/605824/36200547-ecb6e69e-1131-11e8-86ae-1de55e65a03e.png)

As you can see, I am getting _both_ the locales I left in _and_ the minified `locales.js` file due to the way that `react-i18nify` currently loads the locales. The real kick in the teeth is that moment isn't even a direct dependency of my project at all, it's just a dependency of several dependencies.

**Comment by flo-sch** [comment]
Thanks for the screen @lyleunderwood, I had that in mind as well, this is why I think `react-i18nify` should not include any locale itself by default.

However, removing it would be a BC break, therefore I think such evolution should be made in the coming 2.0.0 branch.

Hopefully I will be able to propose some starting point this week or the one after... (I am a bit busy at the moment).

**Comment by lyleunderwood** [comment]
@flo-sch Until then I will probably put together a fork which just removes the offending line to use for my own purposes.

Keep up the good work, all!

**Comment by flo-sch** [comment]
Sure, you can always do that ;)

**Comment by flo-sch** [comment]
Actually @lyleunderwood, as you are using webpack, have you tried the ContextReplacementPlugin?

It might be a quick fix solving your issue?
It works for me with `webpack@3.10`, not sure about version 2 but it's worth trying it IMO :)

However is that it requires you to set the available locales in the webpack config... But adding locales is probably not supposed to change on a daily basis.

```
// webpack.config.js

module.export = {
    // ...
    plugins: [
        new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /en-gb|fr|de|es|it|ja|ko|zh-cn/),
        // ...
    ]
};
```

**Comment by iamakulov** [comment]
@flo-sch Coming here from https://github.com/iamakulov/moment-locales-webpack-plugin/issues/4 – JFYI, MomentLocalesPlugin already uses ContextReplacementPlugin under the hood, so that won’t help :/

As far as I understand, the problem here is that locales are not only included in full, but included _twice_. On the @lyleunderwood’s size, this can be fixed by either of:

* using MomentLocalesPlugin (or ContextReplacementPlugin) to strip locales included as separate files + forking the repo to remove the `moment/min/locales` import

* using MomentLocalesPlugin (or ContextReplacementPlugin) to strip locales included as separate files + using [IgnorePlugin](https://webpack.js.org/plugins/ignore-plugin/) to prevent webpack from bundling the `moment/min/locales` import.

In the latter case, the plugin usage might look like this (I haven’t tested this though):

```js
// webpack.config.js
module.exports = {
  plugins: [
    new webpack.IgnorePlugin(/moment\/min\/locales/, /react-i18nify/),
  ]
}
```

**Comment by lyleunderwood** [comment]
@iamakulov 
![image](https://user-images.githubusercontent.com/605824/36286337-26b7ac56-1264-11e8-858a-9470655a9d38.png)
This does the trick, thanks! Reduces my bundle size from over 1M to ~600K.

**Comment by lyleunderwood** [comment]
I'll note, however, that moment.js is still shockingly large.

**Comment by gerbenmeyer** [comment]
For those who're interested, I started working on v2 of `react-i18nify`, in which `moment.js` has been replaced with `date-fns`. Feel free to check out the [v2 branch](https://github.com/JSxMachina/react-i18nify/tree/v2) or to install it with the next tag `npm i react-i18nfiy@next` and let me know what you think.

**Comment by flo-sch** [comment]
Nice! I gave up on the conditional build with webpack unfortunately, did not found the way the compile with either moment or date-fns :(

**Comment by flo-sch** [comment]
NB: `date-fns@2.0.0` not yet released, according to last issues, could be soon?

**Comment by gerbenmeyer** [comment]
Just released v2 of this library, which doesn't use moment, but date-fns v2 instead!
