### ISSUE TITLE
Extend translations Object

### ISSUE THREAD

**Issue by tamnvt** [sealninja/react-i18nify#47]
I am writing an app using react-i18nify as dependency and a library for that app using that one also. I call setTranslation api in bootstrap file. The problem is that setTranslation api do replace the old translation object with the new one so I can't extend that object in my library which was imported later. So can you adjust source code for open-modified option.

**Comment by gerbenmeyer** [comment]
Interesting issue. I'm just wondering, maybe you'd be better of using the `setTranslationsGetter` function? In that case, you would be fully in control of the translations object yourself.

**Comment by tamnvt** [comment]
setTranslationsGetter is also a considerable option. But in my opinion, this is not configurable. And it's painful if you have many components (loaded lazily) which has their own translation object. The getter function must have an utility somewhere for memorizing the old object and extend with the new object  in every apps using react-i18nify. And for me, that's not a good approach because the app is not responsible for translation object storage.

**Comment by gerbenmeyer** [comment]
I see your point. Would adding a `getTranslations` function which returns the current translation object suffice for you? Because I would consider implementing something like deep merging translations objects with setTranslation a bit too tricky.

**Comment by tamnvt** [comment]
`getTranslations` will not solve the problem. Anyway it makes sense to me to have that work around. At least the user have an ability to extend their previous trans objects by them self and their's no need to store that object on their apps. By that way, I think you just passing prev trans object in setTranslationsGetter paramter. Thanks.

**Comment by gerbenmeyer** [comment]
So I will definitely add `getTranslations` (and `getLocale`) to the next version. Passing the previous translation object in the with `setTranslationsGetter` provided function is kind of impossible though, as when that function is used, no translations are stored in `react-i18nify`...

**Comment by tamnvt** [comment]
Many thanks for your support. :)

**Comment by gerbenmeyer** [comment]
Just released v2 of this library, which has a `getTranslations` and a `getLocale` helper!
