### ISSUE TITLE
i18n  imports 'moment/min/locales'

### ISSUE THREAD

**Issue by Crazy-Ivan** [sealninja/react-i18nify#49]
Hey 

I have found out that i18n requires 'moment/min/locales' which is huge (150kb -> 42kb gzipped). I think in many cases all locales are not needed. Is there any option to include only those which are needed?

**Comment by gerbenmeyer** [comment]
We're actually working on moving to date-fns, which is a lot smaller, so then this shouldn't be an issue anymore :)

**Comment by principat** [comment]
Here is little workaround with webpack:

create a file named locales.js and place it in the vendor folder in the root of your project:

```
// this is a workaround to only import needed locals

for (const name of ['en-gb', 'de', 'fr', 'es', 'it', 'fi']) {
  require(`moment/locale/${name}`)
}
```

and add the following Plugin configuration to your webpack.config.js:
```
/**
 * this is a workaround to only export needed locals by using my one locals
 * definition file
 */
new webpack.NormalModuleReplacementPlugin(
  /moment\/min\/locales/, path.resolve(__dirname, 'vendor/locales.js')
),
// only export locales that are used
new webpack.ContextReplacementPlugin(
  /moment[\/\\]locale$/, /(en-gb|de|fr|es|it|fi)$/
),
```

**Comment by gerbenmeyer** [comment]
Just released v2 of this library, which doesn't use moment, but date-fns v2 instead!
