### ISSUE TITLE
Typescript declarations

### ISSUE THREAD

**Issue by mastacheata** [sealninja/react-i18nify#55]
We're currently in the process of adopting your I18n package in favor of the redux one for our project and would really like to have the typescript hints as well.

Apparently noone has yet moved forward to declare the types in the @DefinitelyTyped project for this library so far. I think it's pretty simple to adapt the ones already declared for the redux one as welll, but I thought it would be best to ask here first before we do that as someone who is neither involved in the typescript nor this project.

I'm using my private Github account for this issue as we have no company policy on open source contributions, but if this is a welcome addition and noone with more experience jumps forward, either me or a colleague would likely go ahead and rewrite the react-redux-i18n types to apply to this library as well according to the guidelines from the typescript documentation.

See:
http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html  
https://www.npmjs.com/package/@types/react-redux-i18n  
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-redux-i18n

**Comment by gerbenmeyer** [comment]
Yeah, I'm not using TypeScript myself, so I would be happy if you could provide a TS definition for this library!

**Comment by kirbycool** [comment]
:+1:
I might be able to find some time to do this. I'm currently using some custom types for a subset of the api, but I can probably adapt the `react-redux-i18n` types.

**Comment by gerbenmeyer** [comment]
It's in the latest version now!
