### ISSUE TITLE
Placeholders/Replacements in "component" translations

### ISSUE THREAD

**Issue by mastacheata** [sealninja/react-i18nify#57]
If I understand the code of the new replace function correctly there's no way to mix placeholders and JSX/HTML translations anymore.

We sadly did this a lot in our application. Sometimes for good reasons, most of the time just because people were lazy.

Example for the lazy scheme that's pretty easy to refactor:

```js
{ 
  transportPricePiece: 'Transportpreis pro Stück: <span class="no-wrap">%{amount}</span>',
}
```

And another one which is not so easy or at least doesn't make much sense to split and refactor:
```js
{
  inquiryDescription: '<strong>Anfrage %{id}</strong> vom %{date}',
}
```

Anyone got any ideas on how to get that working with v2, without spending countless hours manually rewriting all the translations?
I know the developer(s) aren't really talkative, but maybe some other users had similar problems and might have an idea?

**Comment by gerbenmeyer** [comment]
That approach was based on `dangerouslySetInnerHTML`, something which should be avoided. If you really want to do this, I guess you could still do something like: `<span dangerouslySetInnerHTML={{ __html: t('inquireDescription;}} />`.
