### ISSUE TITLE
Including all `date-fns` locales bloats bundle size

### ISSUE THREAD

**Issue by kirbycool** [sealninja/react-i18nify#58]
The library imports all locales from `date-fns`, which leads to an unnecessarily large bundle size.
https://github.com/sealninja/react-i18nify/blob/f4de338a84ad31f715cc28542d70c0fa81a530cd/src/lib/core.js#L7

You can see `date-fns` takes up about 90% of the total library size https://bundlephobia.com/result?p=react-i18nify@2.1.2

Here's an example from a recent project:
<img width="533" alt="image" src="https://user-images.githubusercontent.com/696150/69084877-00e98780-09fa-11ea-84d9-c94f5286cfe0.png">

This issue brought up the issue for `moment`, but moving to `date-fns` still has the same issue
https://github.com/sealninja/react-i18nify/issues/49

As far as solutions, I think the usual webpack workarounds (someone posted a moment example in the old ticket). I'm not sure how else to solve this problem other than letting users configure and pass their own locale object, rather than importing it int `react-18nify`

**Comment by gerbenmeyer** [comment]
Agreed, moving to date-fns didn't have the desired effect with respect to the bundle size. I'm considering only including locale enUS as default, and having a function `addLocale` to add additional locales when needed.

**Comment by kirbycool** [comment]
That sounds like a pretty reasonable approach to me :+1:

**Comment by gerbenmeyer** [comment]
Seems a lot better now: https://bundlephobia.com/result?p=react-i18nify@3.0.0 :smile:
