### ISSUE TITLE
Usage with React hooks and SSR

### ISSUE THREAD

**Issue by ivan-kleshnin** [sealninja/react-i18nify#63]
How **react-i18nify** should be used (initialized) with React hooks? With SSR and React hooks in particular. 

https://github.com/sealninja/react-ssr-example demonstrates the usage for React + LifecycleEvents. I didn't find anything about hooks there, or in the docs, or in the issues.

---

My current attempt (NextJS + React-I18nify):

```js
// pages/_app.js -- global App component

import ...

addLocales({en, ru})
setTranslations(translations)
let initialized = false

export default function App({Component, pageProps}) {
  let router = useRouter()

  let value = {
    lang: router.query.lang,
  }

  if (typeof window == "undefined") {
    console.log("Is called per request on the server! Race conditions?")
    setLocale(router.query.lang)
  } else {
    if (!initialized) {
      initialized = true
      console.log("Is called once on the client!")
      setLocale(router.query.lang)
    }
  }
```

If there's any concurrency between different requests, the above is broken because `setLocale` from one request will affect the mutable state used in another request.

---

According to [the docs at Zeit](https://docs-31e8787wy.zeit.sh/docs/v2/deployments/concepts/lambdas#versus-processes-and-containers) we should be safe in Serverless environments:

> Lambdas have a lot of benefits over booting up and managing containers or processes, let alone computers or clusters.

> **One of the main benefits is that the developer only needs to reason about one concurrent computation happening in the context of their code, despite many of them being able to run in parallel.**

> In the example above, api/index.js handles an incoming request, runs some computation, and responds. **If another request comes to the same path, the system will automatically spawn a new isolated function, thus scaling automatically.**

> In contrast, processes and containers tend to expose an entire server as their entrypoint. That server would then define code for handling many types of requests.

> The code you specify for handling those requests would share one common context and state. Scaling becomes harder because it is hard to decide how many concurrent requests the process can handle.

> Furthermore, if a systemic error occurs when handling an incoming request or event, the entire process or container would be affected, and with it many other requests being handled inside it.

Would like to hear your opinion on this topic, guys.

**Comment by ivan-kleshnin** [comment]
#### Update

I settled on the following solution:

```js
let useIsomorphicLayoutEffect = typeof window !== 'undefined' ? useLayoutEffect : useEffect

function Root() {
  let {lang = "ru"} = useRouter().query

  // No screen flashes and no SSR warnings. 2 render phases for non-default locales
  useIsomorphicLayoutEffect(() => {
    if (lang != getLocale()) {
      setLocale(lang)
    }
  })
}
```

It works but has a "side-effect" of having two render phases for non-default languages.

**Comment by gerbenmeyer** [comment]
Is there any reason why you can't just do the following:

```
export default function App({Component, pageProps}) {
  let router = useRouter();
  setLocale(router.query.lang);

  ...
}
```

I'm typically using a similar approach in my SSR applications. No hooks are needed in this way.

**Comment by ivan-kleshnin** [comment]
Mutable operations called without `useEffect` (`useState`, etc) has a potential of causing

```
Update during the hydration
```

warning. And I certainly had one with the approach you're describing. Those aren't just warning but cues that we have a lot of unnecessary rerenders.

My current code looks like this:

```
// TODO can we do better?
  // https://github.com/sealninja/react-i18nify/issues/63
  if (typeof window == "undefined") {
    if (lang && lang != getLocale()) {
      setLocale(lang)
    }
  }
```

Then I intercept `Link` clicking and `setLocale` before re-routing. This way I have no warnings.

**Comment by gerbenmeyer** [comment]
As far as I know, it will only cause an update during the hydration, if the value for `lang` is different on for the server side and client side render. In case of the `router.query.lang` as you described, the query parameter should be the same on both sides, right? I'm not using NextJS though, so I'm not sure about the behavior in that case.

**Comment by ivan-kleshnin** [comment]
That's a different warning. The one you've just desribed looks like:

```
Hydration mismatch
```

**Comment by gerbenmeyer** [comment]
That would be helpful, as I don't understand yet why `setLocale` would cause any update, as it's not changing any props or state.

**Comment by ivan-kleshnin** [comment]
Looks like the following works fine:

```js
function App(props) {
  let {lang} = useRouter().query

  if (lang != getLocale()) {
    setLocale(lang, false) // forceRerender = false !!!
  }

  ...
}
```

Thanks for the dialogue, Gerben.

**Comment by gerbenmeyer** [comment]
Ah, of course, the `rerenderComponents` argument. I guess that you could even drop the `if (lang != getLocale()) {` then :)
